name: 'Run Tests in Docker'
description: 'Runs LMQLs test suite in a Docker container'

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile.tests'